os:
 - linux
 - osx
osx_image: xcode8.3
dist: trusty
sudo: required
language: c
env:
 - BUILD_TYPE=Debug
 - BUILD_TYPE=Release
matrix:
  include:
    - os: linux
      env:
        ANALYZE="scan-build-3.6 --use-cc clang-3.6 --use-c++ clang++-3.6 "
      compiler: clang
branches:
  only:
    - master
    - coverity_scan
    - /wildmidi-.*$/

before_install:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./CI/before_install.linux.sh; fi
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./CI/before_install.osx.sh; fi
before_script:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./CI/before_script.linux.sh; fi
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./CI/before_script.osx.sh; fi
script:
 - cd ./build
 - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ${ANALYZE}make -j3; fi

notifications:
  irc:    
    channels:
      - "chat.freenode.net#wildmidi"
    on_success: change
    on_failure: always    
